"use client";
import { useRef, useState } from "react";
import type { PublicBusiness, ServiceRequestInput } from "../lib/publicScheduling/domain";

type Receipt = { reference: string; status: string; submittedAt: string };
export type PublicPageBusiness = Pick<PublicBusiness, "slug" | "displayName" | "rules"> & { requestTypes: Pick<PublicBusiness["requestTypes"][number], "id" | "publicLabel" | "active" | "displayOrder">[] };
const initial: ServiceRequestInput = { requestTypeId: "", customerName: "", phone: "", email: "", preferredContact: "phone", address: "", description: "", preferredDate: "", timeWindowId: "", flexibility: "flexible", urgency: "routine", notes: "", consent: false, website: "" };
export default function RequestForm({ business }: { business: PublicPageBusiness }) {
  const [value, setValue] = useState(initial), [step, setStep] = useState(1), [busy, setBusy] = useState(false), [error, setError] = useState(""), [receipt, setReceipt] = useState<Receipt | null>(null);
  const key = useRef<string | null>(null);
  const heading = useRef<HTMLHeadingElement>(null);
  function update<K extends keyof ServiceRequestInput>(field: K, next: ServiceRequestInput[K]) { setValue(previous => ({ ...previous, [field]: next })); key.current = null; setError(""); }
  function go(next: number) { setStep(next); setError(""); requestAnimationFrame(() => heading.current?.focus()); }
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (step < 3) { go(step + 1); return; }
    if (busy) return;
    setBusy(true); setError("");
    key.current ??= crypto.randomUUID();
    try {
      const response = await fetch(`/api/public-scheduling/${encodeURIComponent(business.slug)}`, { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": key.current }, body: JSON.stringify(value) });
      const result = await response.json();
      if (!response.ok) { setError([result.error, ...Object.values(result.fields ?? {})].filter(Boolean).join(" ") || "We couldn’t send your request. Your details are still here. Please try again."); return; }
      setReceipt(result.request);
    } catch { setError("Connection interrupted. Your details are still here. Retry to safely send the same request."); }
    finally { setBusy(false); }
  }
  if (receipt) return <section className="schedule-card schedule-success" aria-live="polite"><div className="schedule-success-icon" aria-hidden="true">✓</div><p className="schedule-eyebrow">REQUEST RECEIVED</p><h2>You’re on our list.</h2><p>{business.displayName} will contact you to review the details and confirm a time.</p><div className="schedule-reference"><small>YOUR REQUEST NUMBER</small><strong>{receipt.reference}</strong></div><p><strong>Your appointment is not yet confirmed.</strong> Keep this reference for your records.</p><p>We’ll reach out by {value.preferredContact === "sms" ? "text" : value.preferredContact} using the contact details you provided.</p><a className="schedule-button" href={`/book/${business.slug}`}>Start another request</a></section>;
  return <section className="schedule-card"><div className="schedule-form-header"><p className="schedule-eyebrow">LET’S MAKE A PLAN</p><h2 ref={heading} tabIndex={-1}>{step === 1 ? "What can we help with?" : step === 2 ? "When & where?" : "Review your request"}</h2><p>{step === 1 ? "Tell us a little about the work and how to reach you." : step === 2 ? "Your preferences help us find the right time." : "Check the details before sending. You can go back to edit."}</p></div><nav aria-label="Request progress" className="schedule-progress">{["The work", "Your visit", "Review"].map((label, index) => <span key={label} aria-current={step === index + 1 ? "step" : undefined} className={step >= index + 1 ? "active" : ""}>{index + 1}<small>{label}</small></span>)}</nav>
    <form onSubmit={submit} aria-busy={busy}>
      {step === 1 && <div className="schedule-fields"><label>Service or request type <select required value={value.requestTypeId} onChange={e => update("requestTypeId", e.target.value)}><option value="">Choose a service</option>{business.requestTypes.filter(type => type.active).sort((a,b) => a.displayOrder-b.displayOrder).map(type => <option key={type.id} value={type.id}>{type.publicLabel}</option>)}</select></label><label>What would you like done? <textarea required minLength={10} maxLength={3000} rows={4} value={value.description} placeholder="For example: repair a sticking door and replace two damaged trim pieces." onChange={e => update("description", e.target.value)}/></label><label>Your name <input required autoComplete="name" maxLength={120} value={value.customerName} onChange={e => update("customerName", e.target.value)}/></label><div className="schedule-grid"><label>Phone <input required type="tel" autoComplete="tel" maxLength={32} value={value.phone} onChange={e => update("phone", e.target.value)}/></label><label>Email <input required type="email" autoComplete="email" maxLength={254} value={value.email} onChange={e => update("email", e.target.value)}/></label></div><label>Best way to contact you <select value={value.preferredContact} onChange={e => update("preferredContact", e.target.value as ServiceRequestInput["preferredContact"])}><option value="phone">Phone call</option><option value="email">Email</option><option value="sms">Text message</option></select></label></div>}
      {step === 2 && <div className="schedule-fields"><label>Service address <textarea required rows={2} autoComplete="street-address" maxLength={500} placeholder="Street, unit, city, state, ZIP" value={value.address} onChange={e => update("address", e.target.value)}/></label><div className="schedule-grid"><label>Preferred date <input required type="date" value={value.preferredDate} onChange={e => update("preferredDate", e.target.value)}/></label><label>Preferred window <select required value={value.timeWindowId} onChange={e => update("timeWindowId", e.target.value)}><option value="">Choose a window</option>{business.rules.windows.map(window => <option value={window.id} key={window.id}>{window.label}</option>)}</select></label></div><p className="schedule-hint">Times are in {business.rules.timeZone.replaceAll("_", " ")}. Requested times are subject to review. Please choose a weekday {Math.ceil(business.rules.minimumLeadHours / 24) + 1}–{business.rules.maximumHorizonDays} days ahead.</p><label>How flexible is your timing? <select value={value.flexibility} onChange={e => update("flexibility", e.target.value as ServiceRequestInput["flexibility"])}><option value="flexible">Flexible — another time is fine</option><option value="preferred">This time is preferred</option><option value="fixed">Please contact me if unavailable</option></select></label><label>How soon do you need help? <select value={value.urgency} onChange={e => update("urgency", e.target.value as ServiceRequestInput["urgency"])}><option value="routine">Routine — no rush</option><option value="soon">Soon — time sensitive</option><option value="urgent">Urgent — please review promptly</option></select></label><label>Anything else? <span className="schedule-optional">Optional</span><textarea maxLength={2000} rows={3} placeholder="Access instructions, parking, or anything we should know. Do not include passwords or payment information." value={value.notes} onChange={e => update("notes", e.target.value)}/></label></div>}
      {step === 3 && <div className="schedule-fields"><dl className="schedule-summary"><dt>Service</dt><dd>{business.requestTypes.find(type => type.id === value.requestTypeId)?.publicLabel}</dd><dt>Work</dt><dd>{value.description}</dd><dt>Contact</dt><dd>{value.customerName}<br/>{value.phone}<br/>{value.email}<br/>Preferred: {value.preferredContact}</dd><dt>Address</dt><dd>{value.address}</dd><dt>Requested visit</dt><dd>{value.preferredDate} · {business.rules.windows.find(window => window.id === value.timeWindowId)?.label}<br/>{value.flexibility} timing · {value.urgency}</dd>{value.notes && <><dt>Notes</dt><dd>{value.notes}</dd></>}</dl><label className="schedule-consent"><input type="checkbox" required checked={value.consent} onChange={e => update("consent", e.target.checked)}/><span>I agree to be contacted about this request using my provided details. I understand this is a request, not a confirmed appointment. Contact preferences do not subscribe me to marketing.</span></label></div>}
      <div className="schedule-trap" aria-hidden="true"><label>Website<input tabIndex={-1} autoComplete="off" value={value.website} onChange={e => update("website", e.target.value)}/></label></div>
      {error && <p role="alert" className="schedule-error">{error}</p>}
      <div className="schedule-actions">{step > 1 && <button disabled={busy} type="button" className="schedule-back" onClick={() => go(step - 1)}>← Back / edit</button>}<button className="schedule-button" disabled={busy} type="submit">{busy ? "Sending request…" : step < 3 ? "Continue →" : "Send service request →"}</button></div><p className="schedule-fine">Please share only the information needed for your service request. No payment is collected here.</p>
    </form>
  </section>;
}

