"""Publish aggregate reproducible experiment tables; optical evidence stays private."""
import json,sys
from pathlib import Path
root=Path(sys.argv[1]);out=Path(sys.argv[2]);r=json.loads((root/'report.json').read_text());p=json.loads((root/'provenance.json').read_text());models=r['models']
lines=['# Phase 3E — frozen real-document recognizer benchmark','',
'Completed locally on 2026-09-20. Eight documents, 24 invoice rows, eight document groups. No new training, production changes, push, deployment or Phase 4 implementation.','',
'## Protocol and limits','',
'Every row is scored once per fixed model/crop/preprocessing condition: 24 automatic + 24 manual, native + one established local-contrast variant = 96 observations per model. All six adapters receive identical hashed input files; truth is loaded only by the scorer. Native automatic results are the primary comparison. No per-row best-of-model or best-of-preprocessing selection.','',
'This is fixed pretrained leave-one-document-out evaluation, not eight newly trained models. No held-out document enters new training because there is no new training. The corpus and enhancement were used in earlier research, so these are retrospective results, not a new independent acceptance set. The fine-tuned Tesseract is a historical comparison only: five documents trained it and C validated it; its 24-row score cannot represent unseen generalization.','',
'Literal ground truth contains 22 INV tokens without printed hyphens and two legacy numeric-only references. Raw exact and whitespace/case normalized exact agree for native automatic results. Canonical normalization inserts only the structural hyphen after INV before digits; it never replaces characters or supplies missing digits. Character accuracy = 1 − CER; CER = (substitutions + insertions + deletions) / truth characters.','',
'Earlier 7-row baseline scores used global autocontrast, 2× resize and padding. This experiment uses native crops as primary, plus the established OCR-v2 local-background contrast enhancement. Those historical numbers are not the same preprocessing condition; no output was chosen to reproduce them.','',
'## Automatic native crops','', '| Model | Exact | Character accuracy | CER | S / I / D |','|---|---:|---:|---:|---:|']
for name,d in models.items():
 g=d['groups']['auto-native'];lines.append(f"| {name}{' (historically trained)' if name=='pilot' else ''} | {g['exact']}/24 ({g['exact']/24:.2%}) | {g['characterAccuracy']:.2%} | {g['CER']:.2%} | {g.get('substitution',0)} / {g.get('insertion',0)} / {g.get('deletion',0)} |")
lines+=['','**Best pretrained: SVTRv2.** PARSeq ties exact accuracy; SVTRv2 has fewer character errors. Both pass the requested approximate aggregate 90% exact / 95% character research gate. This does not establish production safety.','','## Crop and preprocessing comparison','','| Model | Auto native | Auto enhanced | Manual native | Manual enhanced |','|---|---:|---:|---:|---:|']
for name,d in models.items():lines.append('| '+name+' | '+' | '.join(str(d['groups'][k]['exact'])+'/24' for k in ['auto-native','auto-enhanced','manual-native','manual-enhanced'])+' |')
lines+=['','Manual crops do not rescue the leading models. Enhancement does not improve their exact accuracy and harms TrOCR. No crop clipping was observed in the inherited crop audit or difficult-row montage.','','## All condition metrics','','| Model / condition | Exact | Character accuracy | CER | S / I / D |','|---|---:|---:|---:|---:|']
for name,d in models.items():
 for condition,g in d['groups'].items():
  lines.append(f"| {name} / {condition} | {g['exact']}/{g['rows']} | {g['characterAccuracy']:.2%} | {g['CER']:.2%} | {g.get('substitution',0)} / {g.get('insertion',0)} / {g.get('deletion',0)} |")
lines+=['','## Format-only constrained decoding','',
'Only PARSeq uses an actual position-logit constrained decoder. It requires an already observed INV prefix and at least four observed suffix positions; numeric positions can select a digit from their existing logits. Length and observed numeric characters are preserved. No business candidates, expected digits, missing-prefix repair or missing-digit generation. Other adapters report **grammar validation only**, not a constrained recognizer. Rejected outputs count as abstentions (empty predictions), so their constrained CER includes deletion penalties. The two numeric-only references are unsupported by this grammar and remain rejected; they are never padded or assigned an invented prefix.','',
'PARSeq native automatic: 21/22 modern tokens correct after the format-only decoder, with both legacy rows rejected (21/24 overall). Raw modern tokens: 20/22. One O→0 correction helps, but another faint row becomes a structurally valid wrong number. SVTRv2 already emits two wrong numeric digits, which syntax cannot repair. Do not use grammar validity as proof of correctness.','','## Eight document folds (native automatic)','', '| Document | Rows | generic | pilot* | PP-OCRv5 | SVTRv2 | PARSeq | TrOCR |','|---|---:|---:|---:|---:|---:|---:|---:|']
for doc,g in models['svtr']['folds']['auto-native'].items():
 lines.append(f"| {doc} | {g['rows']} | "+' | '.join(f"{d['folds']['auto-native'][doc]['exact']}/{g['rows']}; {d['folds']['auto-native'][doc]['characterAccuracy']:.2%}" for d in models.values())+' |')
lines+=['','Cells: exact rows; character accuracy. *Pilot folds include historical training exposure. Full per-fold metrics for all four conditions are in private report.json.','','## Error localization and optical information','',
'Every incorrect token across all conditions has an alignment and error categories in private report.json. Categories distinguish prefix corruption, leading garbage, digit substitutions/deletions/insertions, and multiple-digit corruption. No evidence supports declaring cropped-off or irretrievably missing glyphs. No printed hyphens exist in this corpus, so hyphen deletion is **not measurable**, not a demonstrated zero failure rate.','',
'All leading-model primary failures are in B. SVTRv2 substitutes 5→3 in B-0 and 5→4 in B-1. PARSeq substitutes 0→O and 5→N in B-1 and 0→O in B-3. B-1 is the strongest common optical difficulty: all four mature models misread the same 5. The montage shows faint, blurred, mottled strokes. That supports an image-quality contribution, but does not prove information is unrecoverable. Several other shared model failures are recovered by another model.','',
'All B rows meet the requested possible-information-limitation flag (two mature models fail at least one same glyph). This flag is diagnostic, not a finding that every B row is unreadable.','',
'3× Lanczos is a separate post-hoc diagnostic, excluded from primary selection. No super-resolution or generated characters were used. Results on B:','', '| Model | Native exact / 5 | 3× upscale exact / 5 | Enhanced exact / 5 |','|---|---:|---:|---:|']
truth={(x['id'],x['kind']):x['label'] for x in json.loads((root/'truth.json').read_text())}
for name in ['ppocr','svtr','parseq','trocr']:
 diag=json.loads((root/(name+'-diagnostic.json')).read_text());n=sum(x['raw'].strip().upper()==truth[x['id'],'auto'] for x in diag['rows']);d=models[name]
 lines.append(f"| {name} | {d['folds']['auto-native']['B']['exact']} | {n} | {d['folds']['auto-enhanced']['B']['exact']} |")
lines+=['','## Confusions (all models, native automatic only)','','| Expected → observed | Count |','|---|---:|']
for pair,count in sorted(r['confusionMatrix'].items(),key=lambda x:-x[1]):lines.append(f'| {pair} | {count} |')
lines+=['','The requested 0/O/U, 1/I/L, 2/Z, 3/S, 4/A, 5/S, 6/G, 7/T, 8/B, 9/R subgroup matrices are included in report.json. Unseen combinations have count zero; numeric-to-numeric confusions remain in the full matrix.','','## Runtime practicality','',
'Measured on local WSL/Ubuntu, RTX 5060 Laptop GPU (8 GB); four CPU threads for Torch/ONNX, one for Tesseract. Recognition-only timings include model preprocessing and decoding, not camera/layout/network. Five-row timing is five sequential calls on an unrelated synthetic token, not a measured complete payment workflow. One warm-up, five measured samples; GPU synchronized. GPU is unavailable for native Tesseract; PP-OCRv5 was measured with the established CPU-only ONNX runtime, so its GPU latency is unmeasured. Diagnostic runs supply cached-weight fresh-process initialization (downloads excluded) and sequential isolated latency samples for the four mature models. Tesseract initializes in each subprocess, included in per-crop time rather than the trivial Python adapter initialization.','', '| Model | Weight MiB | Init seconds | CPU ms/crop | GPU ms/crop | Five CPU / GPU ms |','|---|---:|---:|---:|---:|---:|']
weightmap=dict(zip(['svtr','parseq','ppocr','pilot','generic','trocr'],p['weights']))
for name,d in models.items():
 q=root/(name+'-diagnostic.json');perf=json.loads(q.read_text()) if q.exists() else d;lat=perf['latency'];cpu=lat['cpu'];gpu=lat.get('cuda');size=weightmap[name]['bytes']/1024**2
 lines.append(f"| {name} | {size:.2f} | {'per subprocess' if name in ['generic','pilot'] else format(perf['initMs']/1000,'.3f')} | {cpu['cropMsMedian']:.2f} | {format(gpu['cropMsMedian'],'.2f') if gpu else 'N/A'} | {cpu['fiveRowsSequentialMs']:.2f} / {format(gpu['fiveRowsSequentialMs'],'.2f') if gpu else 'N/A'} |")
lines+=['',
'SVTRv2, PARSeq and TrOCR need Python + PyTorch; PARSeq also uses timm/Lightning and TrOCR Transformers. PP-OCRv5 uses RapidOCR + ONNX Runtime. Tesseract uses native Tesseract/Leptonica. All inference is local; pretrained assets were downloaded once from the maintainers. HF offline mode was verified for diagnostic execution.','',
'Recommended deployment if later approved: a persistent private inference service, with Vercel handling authenticated orchestration. CPU service is already plausible at these line-crop times; a GPU is not necessary merely to achieve sub-second five-line recognition. Tesseract/PP-ONNX could potentially fit a carefully packaged CPU function; Torch models require explicit packaging and cold-start testing. No claim that Vercel cannot host them: current documented Python bundles allow 500 MB and eligible large functions up to 5 GB beta, with 2–4 GB memory. These limits make the current CUDA development environment unsuitable as-is. A private service is the simpler predictable option, not an architecture implemented here. [Vercel limits](https://vercel.com/docs/functions/limitations).','','## Model provenance','',
'- [SVTRv2 official source](https://github.com/Topdu/OpenOCR); weights https://github.com/Topdu/OpenOCR/releases/download/develop0.0.1/openocr_svtrv2_ch.pth','- [PARSeq official source](https://github.com/baudm/parseq); weights https://github.com/baudm/parseq/releases/download/v1.0.0/parseq-bb5792a6.pt','- [Microsoft TrOCR small printed](https://huggingface.co/microsoft/trocr-small-printed), snapshot 04e994ab854b0089d4929f48c2b4dbe2ce78a340.','- PP-OCRv5: same English mobile ONNX model as the preceding generic baseline.','', '| Model | SHA-256 |','|---|---|']
for name,w in weightmap.items():lines.append(f"| {name} | `{w['sha256']}` |")
lines+=['','Source commits: '+json.dumps(p['sourceCommits']), '', 'Runtime packages: '+json.dumps(p['packages']), '',
'## Reproduction and validation','',
'Run phase3e_prepare.cjs with the frozen generalization-v1 corpus and a new private output directory. Run phase3e_benchmark.py once per model (CUDA for svtr/parseq/trocr). Run phase3e_report.py, then the four mature models with --diagnostic, then phase3e_validate.py and phase3e_markdown.py. Scripts accept paths explicitly; no corpus/model files are committed.','',
'Validation passed: 96 immutable input hashes and matching prediction provenance; six complete 96-observation matrices; eight disjoint document groups; no duplicate input observations; suffix-length preservation; unsupported/missing content abstention; controlled character-class ambiguity; edit-distance substitution/insertion/deletion checks. Adapter input manifests contain no labels. Node syntax and Python compilation passed. No production build was needed because only offline research scripts/report changed. SVTR checkpoint loading reported only missing BatchNorm num_batches_tracked counters, irrelevant in eval mode; no learned parameter omissions. Its generic loader logs “finetune from checkpoint” when loading pretrained weights, but no optimizer, backward pass or training ran.','',
'Private artifacts: %LOCALAPPDATA%/Trimax/ocr-v2-training/phase3e (inputs/truth/protocol, six raw result files, four diagnostic files, full metrics/error/confusion report, difficult-crop montage and weight hashes). Installation logs and cloned model source: ~/trimax-ocr/phase3e; isolated Python: ~/trimax-ocr/benchmark-venv.','',
'## Decision','',
'Recommend pretrained SVTRv2 as the lead invoice architecture, retaining PARSeq as a research comparator. Do not fine-tune on these same eight documents yet. Collect a fresh diverse real-document acceptance set, particularly faint print; lock the selected model first. Aggregate 22/24 is encouraging but the sample is small, prior research exposed the documents, and B is only 3/5 for SVTRv2.','',
'READY FOR OCR v2 PHASE 4: **yes for a separately authorized offline research phase**, based on the specified aggregate gate; **not production/payment readiness**. Any future fusion must retain uncertainty and abstain on valid-looking wrong numbers. Phase 4 was not begun.','',
'Amounts and totals preserved: no files in those paths changed. Prior aggregate recognition findings are inherited, not rerun or improved by this invoice-only experiment. Production changed: no. Push/deployment: none.']
out.write_text('\n'.join(lines)+'\n',encoding='utf-8');print(out)
