import assert from 'node:assert/strict';
import {getPublicBusiness} from '../src/app/lib/publicScheduling/domain.ts';
import {submitProductionRequest} from '../src/app/lib/publicScheduling/productionService.ts';
import {createSchedulingPersistence} from '../src/app/lib/publicScheduling/productionAdapter.ts';
import {enforceProductionAbuse,type AbuseProviders} from '../src/app/lib/publicScheduling/abuseProtection.ts';
import {createStatusCapability,verifyStatusCapability,publicStatusProjection} from '../src/app/lib/publicScheduling/capability.ts';
import {validateOutboxIntent,recordDeliveryFailure,type OutboxIntent} from '../src/app/lib/publicScheduling/outbox.ts';
import {disabledConversion,validateConversionPlan} from '../src/app/lib/publicScheduling/conversion.ts';
const business=getPublicBusiness('rnl-creations')!;
const value={requestTypeId:'repair',customerName:'Test',phone:'',email:'test@example.com',preferredContact:'email',address:'Test address',description:'Repair',preferredDate:'',timeWindowId:'',flexibility:'flexible',urgency:'routine',notes:'',consent:true};
const capability=createStatusCapability();assert.equal(capability.token.length,43);assert.equal(capability.hash.length,64);assert.notEqual(createStatusCapability().token,capability.token);
assert.equal(verifyStatusCapability(capability.token,capability.hash,'2099-01-01'),true);assert.equal(verifyStatusCapability(createStatusCapability().token,capability.hash,'2099-01-01'),false);assert.equal(verifyStatusCapability(capability.token,capability.hash,'2000-01-01'),false);
assert.deepEqual(Object.keys(publicStatusProjection({reference:'test',status:'approved',submittedAt:'today'})).sort(),['reference','status','submittedAt']);
assert.equal(publicStatusProjection({reference:'test',status:'approved',submittedAt:'today'}).status,'under_review');
assert.equal(publicStatusProjection({reference:'test',status:'approved',submittedAt:'today',confirmationStatus:'confirmed'}).status,'confirmed');
const calls:{name:string;args:Record<string,unknown>}[]=[];
const adapter=createSchedulingPersistence({async rpc(name,args){calls.push({name,args});return {data:{id:'test-id',reference:'opaque-reference',status:'pending_confirmation',submittedAt:'2026-10-09'},error:null};}},async slug=>slug===business.slug?business:null);
const submission={slug:business.slug,input:value,idempotencyKey:'idempotent-key-123456',capabilityHash:capability.hash};
assert.equal((await adapter.submit(submission)).reference,'opaque-reference');assert.equal(calls.length,1);assert.equal(calls[0].name,'trimax_submit_public_service_request');assert.equal('businessId' in calls[0].args,false);assert.equal((calls[0].args.p_payload as Record<string,unknown>).businessId,undefined);
await assert.rejects(adapter.submit({...submission,input:{...value,businessId:'wrong-tenant'}}),/Unexpected/);
await assert.rejects(adapter.submit({...submission,slug:'unknown'}),/unavailable/);
await assert.rejects(adapter.submit({...submission,input:{...value,consent:false}}),/Invalid/);
const abuseInput={businessSlug:'one',trustedClientIdentity:'test-trusted-address',challengeToken:'verified-challenge'};
assert.equal((await enforceProductionAbuse(abuseInput)).allowed,false);
const providers:AbuseProviders={fingerprintSecret:'x'.repeat(32),rateLimit:{async consume(input){assert.ok(!input.key.includes('test-trusted-address'));return {allowed:true};}},challenge:{async verify(input){assert.equal(input.action,'public-scheduling');return {verified:true};}}};
assert.equal((await enforceProductionAbuse(abuseInput,providers)).allowed,true);
assert.equal((await enforceProductionAbuse(abuseInput,{...providers,rateLimit:{async consume(){return {allowed:false};}}})).allowed,false);
assert.equal((await enforceProductionAbuse(abuseInput,{...providers,challenge:{async verify(){return {verified:false};}}})).allowed,false);
assert.equal((await enforceProductionAbuse(abuseInput,{...providers,challenge:{async verify(){throw Error('Provider offline');}}})).allowed,false);
const productionInput={...submission,challengeToken:'challenge',trustedClientIdentity:'trusted-address'};
const beforeProduction=calls.length;await assert.rejects(submitProductionRequest(productionInput,{persistence:adapter}),/blocked/);assert.equal(calls.length,beforeProduction);
await assert.rejects(submitProductionRequest(productionInput,{persistence:adapter,abuseProviders:{...providers,challenge:{async verify(){return {verified:false};}}}}),/blocked/);assert.equal(calls.length,beforeProduction);
await submitProductionRequest(productionInput,{persistence:adapter,abuseProviders:providers});assert.equal(calls.length,beforeProduction+1);
const intent:OutboxIntent={businessId:'one',requestId:'request',event:'request_received',channel:'sms',audience:'customer',recipient:'test-phone',idempotencyKey:'intent-key-12345678',scheduledFor:'2099-01-01',consentReference:null,template:'received',parameters:{}};
assert.throws(()=>validateOutboxIntent(intent),/consent/);assert.equal(validateOutboxIntent({...intent,consentReference:'verified-consent-event'}).channel,'sms');
assert.equal(recordDeliveryFailure({state:'retry',attempts:4,nextAttemptAt:'',providerMessageId:null,lastErrorCode:null},'provider_offline').state,'dead_letter');
const plan={requestId:'request',businessId:'one',approvedBy:'owner',idempotencyKey:'conversion-key-12345',client:{kind:'attach' as const,clientId:'reviewed-client'},target:'queue' as const};assert.equal(validateConversionPlan(plan),true);await assert.rejects(disabledConversion.convert(plan),/not enabled/);
console.log('Phase 2 adapter/abuse/capability/outbox/conversion regressions PASS');
