import { goldenCoverageBlockers } from "./fixtures/remittance/coverage.ts";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createRemittanceEvidence, resolveRemittanceAttempt, selectObservedHeader, attemptAllowsApply, type RemittanceEvidence, type OcrPass } from "../src/app/lib/remittanceAttempt.ts";
import { normalizeInvoiceColumnToken } from "../src/app/lib/ocrStructure.ts";
import type { RemittanceInvoiceRecord, StructuredRemittanceRowEvidence } from "../src/app/lib/remittanceMatching.ts";
import type { DuplicateRemittanceActivity } from "../src/app/lib/duplicateRemittance.ts";
type Fixture = {id:string;split:boolean;expected:{checkNumber:string;checkDate:string;payor:string;total:number;rowCount:number;invoiceNumbers:string[];invoiceIds:string[];units:(string|null)[];amounts:number[];duplicate:string;applyEligible:boolean}};
const fixtures: Fixture[] = JSON.parse(readFileSync("scripts/fixtures/remittance/golden.json", "utf8"));
const context = { role:"owner",receivedDate:"2026-09-17",fingerprint:"" };
const pass = (text:string,variant="original"):OcrPass => ({text,region:"document",variant,pageMode:"sparse",confidence:90,words:[]});
function setup(f:Fixture){
  const e=f.expected;
  const rows:StructuredRemittanceRowEvidence[]=e.invoiceNumbers.map((number,i)=>({rowId:`row-${i+1}`,y:100+i*24,height:16,text:`${number} ${e.units[i]??""} Paint $${e.amounts[i].toFixed(2)}`,source:{region:"document",variant:"original",pageMode:"sparse"},rawInvoiceLikeTokens:[number],normalizedInvoiceCandidates:[number],unitLikeTokens:e.units[i]?[e.units[i]!]:[],dateTokens:[],amountCandidates:[{raw:e.amounts[i].toFixed(2),value:e.amounts[i],selected:true}]}));
  const rawPasses=[pass(`PAYOR: ${e.payor}\nCHECK DATE: ${e.checkDate} CHECK #: ${e.checkNumber}\n${rows.map(row=>row.text).join("\n")}\nTOTAL $${e.total.toFixed(2)}`)];
  const evidence=createRemittanceEvidence({attemptId:`golden-${f.id}`,capture:{source:"fixture",image:{width:2000,height:1200,bytes:1,mime:"image/jpeg"},quality:{},sources:[],selectionReason:"fixture"},rawPasses,headerEvidence:selectObservedHeader(rawPasses,rows),physicalRows:rows,assignments:[],diagnostics:[]});
  const invoices:RemittanceInvoiceRecord[]=e.invoiceNumbers.map((number,i)=>({id:e.invoiceIds[i],displayId:number,customerName:e.payor,projectTitle:`${e.units[i]??""} Paint`,invoiceAmount:e.amounts[i],amountPaid:0,status:"sent",splitParentInvoiceId:f.split?'source-parent':null}));
  if(f.split)invoices.push({id:"source-parent",displayId:e.invoiceNumbers[0],customerName:e.payor,projectTitle:"Split source",invoiceAmount:e.total,amountPaid:0,status:"sent",splitChildrenCount:e.rowCount});
  return {evidence,invoices,rows,rawPasses};
}
for(const fixture of fixtures){
  const {evidence,invoices}=setup(fixture), e=fixture.expected;
  const before=JSON.stringify({evidence,invoices});
  const result=resolveRemittanceAttempt(evidence,invoices,[],context);
  assert.equal(result.reconciliationResult.eligible,e.applyEligible,fixture.id+': '+result.reconciliationResult.blockers.join('; '));
  assert.equal(result.evidence.headerEvidence.checkNumber,e.checkNumber);
  assert.equal(result.evidence.headerEvidence.checkDate,e.checkDate);
  assert.equal(result.reconciliationResult.documentTotal,e.total);
  assert.equal(result.evidence.physicalRows.length,e.rowCount);
  assert.deepEqual(result.reconciliationResult.reviewIds,[...e.invoiceIds].sort());
  assert.equal(result.duplicateResult.status,e.duplicate);
  assert(attemptAllowsApply(result,e.invoiceIds,e.invoiceIds,e.total,false));
  assert.equal(attemptAllowsApply(result,e.invoiceIds.slice(1),e.invoiceIds,e.total,false),false);
  assert.equal(attemptAllowsApply(result,[...e.invoiceIds,e.invoiceIds[0]],e.invoiceIds,e.total,false),false);
  assert.equal(attemptAllowsApply(result,e.invoiceIds,e.invoiceIds,e.total+1,false),false);
  assert.equal(attemptAllowsApply(result,e.invoiceIds,e.invoiceIds,e.total,true),false);
  assert.deepEqual(resolveRemittanceAttempt(evidence,invoices,[],context),result);
  assert.equal(JSON.stringify({evidence,invoices}),before);
  assert(Object.isFrozen(result.evidence.physicalRows[0].amountCandidates[0]));
  assert.throws(()=>{(result.evidence as unknown as RemittanceEvidence).attemptId='overwrite';});
  const paid=structuredClone(invoices);paid[0].status='paid';paid[0].amountPaid=paid[0].invoiceAmount;
  assert.equal(resolveRemittanceAttempt(evidence,paid,[],context).reconciliationResult.eligible,false);
}
const {evidence,invoices,rows}=setup(fixtures[1]);
const run=(change:(value:RemittanceEvidence)=>void, db=invoices)=>{const copy=structuredClone(evidence) as RemittanceEvidence;change(copy);return resolveRemittanceAttempt(createRemittanceEvidence(copy),db,[],context);};
assert.equal(run(e=>{e.headerEvidence.documentTotal=null;}).reconciliationResult.eligible,false);
assert.equal(run(e=>{e.headerEvidence.checkNumber=null;}).evidence.headerEvidence.checkNumber,null);
assert.equal(run(e=>{e.physicalRows=[];}).reconciliationResult.eligible,false);
assert.equal(run(e=>{e.capture.sources=[{id:'canvas',status:'failure',stage:'http',error:'synthetic'}];}).reconciliationResult.eligible,false);
assert.equal(run(e=>{e.physicalRows.push(structuredClone(e.physicalRows[0]));}).reconciliationResult.eligible,false);
assert.equal(run(e=>{e.physicalRows[0].text='U05 Paint 1099.00';e.physicalRows[0].normalizedInvoiceCandidates=[];e.physicalRows[0].rawInvoiceLikeTokens=[];}).reconciliationResult.eligible,false);
assert.equal(run(e=>{e.physicalRows[0].text='INV-0513 X99 Paint 1099.00';e.physicalRows[0].unitLikeTokens=['X99'];}).reconciliationResult.eligible,false);
for(const status of ['void','corrected','draft']){const db=structuredClone(invoices);db[0].status=status;assert.equal(run(()=>{},db).reconciliationResult.eligible,false);}
const partial=structuredClone(invoices);partial[0].amountPaid=50;assert.equal(run(()=>{},partial).reconciliationResult.eligible,false);
assert.equal(run(()=>{},[...invoices,{...invoices[0],id:'other-same-unit',displayId:'INV-0999'}]).reconciliationResult.eligible,true,'Same unit cannot introduce an unobserved invoice candidate.');
for(const [raw,expected] of [['INVOS19','INV-0519'],['INV05L9','INV-0519'],['INV05I9','INV-0519'],['0519','INV-0519']])assert.equal(normalizeInvoiceColumnToken(raw,true),expected);
assert.equal(selectObservedHeader([pass('INV0513 U05 29.00\nINV0514 H10 99')],rows).documentTotal,null);
assert.equal(selectObservedHeader([pass('TOTAL 2, 49')],rows).documentTotal,null);
assert.equal(selectObservedHeader([pass('CHECK DATE 2026-08-19\nINV0513 08/01/2026 1099.00')],rows).checkDate,'2026-08-19');
const activities:DuplicateRemittanceActivity[]=invoices.map(invoice=>({id:'activity-'+invoice.id,action:'invoice.batch_payment_applied',entityId:invoice.id,entityLabel:invoice.displayId,createdAt:'2026-08-20T12:00:00Z',details:{invoiceId:invoice.id,invoiceNumber:invoice.displayId,paymentReference:'2797',checkAmount:5495,payor:'North Creek Apartments',checkDate:'2026-08-19',receivedDate:'2026-08-20',batchInvoiceCount:5,remittanceDocumentFingerprint:'a'.repeat(256)}}));
assert.equal(resolveRemittanceAttempt(evidence,invoices,activities,context).reconciliationResult.eligible,false);
const different=structuredClone(evidence) as RemittanceEvidence;different.headerEvidence.checkNumber='12345';different.headerEvidence.checkDate='2026-09-01';
const sameTemplate=resolveRemittanceAttempt(createRemittanceEvidence(different),invoices,activities,{...context,fingerprint:'a'.repeat(256)});
assert.notEqual(sameTemplate.duplicateResult.confidence,'exact');
const component=readFileSync('src/app/components/BatchInvoicePayments.tsx','utf8');
assert(!component.includes('parsedTotalFromLines'));
assert(!component.includes('function reconcileReviewMatches'));
assert(component.includes('attemptAllowsApply(activeRemittanceAttempt'));
assert(readFileSync('vercel.json','utf8').includes('scripts/remittance-release-gate.ts'));
assert.deepEqual(goldenCoverageBlockers(JSON.parse(readFileSync('scripts/fixtures/remittance/golden.json','utf8'))), []);
assert.deepEqual(goldenCoverageBlockers(['A','B','C','D'].map(id=>({id,physicalTruthComplete:true}))),[]);
console.log('Golden remittance contract matrix A/B/C/D/E passed; immutable replay, unknown values, eligibility, exact sets, duplicate and adversarial guards passed.');

assert.deepEqual(goldenCoverageBlockers([{id:'A',physicalTruthComplete:true},{id:'B',physicalTruthComplete:true},{id:'C',physicalTruthComplete:true}]), ['Required physical fixture D has no complete verified expected-value record.']);
