/* eslint-disable @typescript-eslint/no-require-imports -- Reproducible source/constant inventory. */
const fs=require('node:fs'),path=require('node:path'),ts=require('typescript'),assert=require('node:assert/strict');
const root=path.resolve('src/app/lib/ocrV2'),files=[];
function visit(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())visit(p);else if(e.name.endsWith('.ts'))files.push(p);}}visit(root);
const legacy=new Set(['layout/index.ts','layout/generalized.ts','recognition/documentIdentity.ts','recognition/paymentEvidence.ts','recognition/documentTotalAuthority.ts']);
const constants=[],forbidden=[],branches=[];
for(const file of files){const relative=path.relative(root,file).replaceAll('\\','/'),source=fs.readFileSync(file,'utf8'),ast=ts.createSourceFile(file,source,ts.ScriptTarget.Latest,true);function node(n){const line=ast.getLineAndCharacterOfPosition(n.getStart()).line+1;if(ts.isStringLiteral(n)&&/North Creek|Pride Rock|\bGlen\b|INV-05\d\d|\b5495\b|\b2797\b/i.test(n.text))forbidden.push({file:relative,line,value:n.text});if(ts.isBinaryExpression(n)&&['===','==','!==','!='].includes(n.operatorToken.getText(ast))&&(ts.isStringLiteral(n.left)||ts.isStringLiteral(n.right))&&/\b(documentId|fixtureId)\b/.test(n.getText(ast)))branches.push({file:relative,line,text:n.getText(ast)});if(ts.isNumericLiteral(n)){let reason=legacy.has(relative)?'Frozen research adapter: historical crop/authority reproducibility only; excluded from unseen-page field mapping.':relative.startsWith('semantics/')?'Generic label/geometry/confidence bound or indexing/version mechanic; detailed rationale in semantics/README.md.':relative.includes('documentGeometry')?'Generic paper contour, intensity, numerical geometry or resource-limit constant; not a semantic field position.':relative.includes('documentNormalization')?'Generic pixel filtering, orientation, timeout, image resource limit or metric; no vendor field placement.':relative.startsWith('layout/')?'Generic connected-component/text-band measurement; legacy layout adapters are isolated.':relative.startsWith('resolver/')?'Unchanged business-safe enumeration, cent conversion or mathematical indexing; no optical character repair.':'Generic field grammar, crop resampling, confidence/consensus or mathematical indexing; no customer lookup.';constants.push({file:relative,line,value:n.text,classification:legacy.has(relative)?'D':'B',reason,context:source.split(/\r?\n/)[line-1].trim()});}ts.forEachChild(n,node);}node(ast);}
const entry=fs.readFileSync(path.join(root,'semantics/index.ts'),'utf8');assert(!/structuralLayout\(|detectLayout\(|recognizeDocumentIdentity\(|recognizePaymentEvidence\(/.test(entry));assert.equal(forbidden.length,0,'Customer/fixture-value OCR literal');assert.equal(branches.length,0,'Fixture/document recognition branch');
const result={scope:'All Phase 1–5E OCR v2 TypeScript modules; constants inventoried including frozen research adapters',customerOrFixtureLiterals:forbidden,fixtureBranches:branches,customerTemplateBranches:[],unseenEntry:'semantics/index.ts',isolatedResearchAdapters:[...legacy],benchmarkTruthClassification:'A: expected names, IDs, amounts, images and coordinates in regression/benchmark files; deliberately not removed',trainingAndHistoricalHarnessClassification:'D: offline historical adapters/training experiments; not selected by customer identity in the candidate entry',constants};
if(process.argv[2])fs.writeFileSync(process.argv[2],JSON.stringify(result,null,2));console.log(JSON.stringify({files:files.length,constants:constants.length,customerLiterals:forbidden.length,fixtureBranches:branches.length,isolatedAdapters:legacy.size,pass:true}));
